//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDE.UITest.PageObjects {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FacilitiesPageCtrls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FacilitiesPageCtrls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDE.UITest.PageObjects.FacilitiesPageCtrls", typeof(FacilitiesPageCtrls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblFacilitiesDisplayText.
        /// </summary>
        internal static string FacilityList {
            get {
                return ResourceManager.GetString("FacilityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgFacilitiesRightArrow.
        /// </summary>
        internal static string FacilityRightArrow {
            get {
                return ResourceManager.GetString("FacilityRightArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgImpersonate.
        /// </summary>
        internal static string Impersonation {
            get {
                return ResourceManager.GetString("Impersonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Impersonation_Cancel {
            get {
                return ResourceManager.GetString("Impersonation_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Impersonation_Ok {
            get {
                return ResourceManager.GetString("Impersonation_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string Impersonation_UserID {
            get {
                return ResourceManager.GetString("Impersonation_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblFirstName.
        /// </summary>
        internal static string LoggedInUser {
            get {
                return ResourceManager.GetString("LoggedInUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgReload.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgSearch.
        /// </summary>
        internal static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtSearchFacilities.
        /// </summary>
        internal static string SearchFacilities {
            get {
                return ResourceManager.GetString("SearchFacilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to md5b60ffeb829f638581ab2bb9b1a7f4f3f.EntryRenderer.
        /// </summary>
        internal static string SearchFacilitiesClass {
            get {
                return ResourceManager.GetString("SearchFacilitiesClass", resourceCulture);
            }
        }
    }
}
