//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDE.UITest.PageObjects {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoginPageCtrls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginPageCtrls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDE.UITest.PageObjects.LoginPageCtrls", typeof(LoginPageCtrls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to okta-signin-submit.
        /// </summary>
        internal static string Okta_Btn_SignIn {
            get {
                return ResourceManager.GetString("Okta_Btn_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to okta-signin-password.
        /// </summary>
        internal static string Okta_TxtBx_Password {
            get {
                return ResourceManager.GetString("Okta_TxtBx_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #okta-signin-password.
        /// </summary>
        internal static string Okta_TxtBx_Password_Css {
            get {
                return ResourceManager.GetString("Okta_TxtBx_Password_Css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to okta-signin-username.
        /// </summary>
        internal static string Okta_TxtBx_UserName {
            get {
                return ResourceManager.GetString("Okta_TxtBx_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #okta-signin-username.
        /// </summary>
        internal static string Okta_TxtBx_UserName_Css {
            get {
                return ResourceManager.GetString("Okta_TxtBx_UserName_Css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #usernameLabel.
        /// </summary>
        internal static string Okta_UserNameLable_Css {
            get {
                return ResourceManager.GetString("Okta_UserNameLable_Css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #cred_sign_in_button.
        /// </summary>
        internal static string Outlook_Btn_SignIn {
            get {
                return ResourceManager.GetString("Outlook_Btn_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cred_password_inputtext.
        /// </summary>
        internal static string Outlook_TxtBx_Password {
            get {
                return ResourceManager.GetString("Outlook_TxtBx_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input#cred_password_inputtext.
        /// </summary>
        internal static string Outlook_TxtBx_Password_Css {
            get {
                return ResourceManager.GetString("Outlook_TxtBx_Password_Css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cred_userid_inputtext.
        /// </summary>
        internal static string Outlook_TxtBx_UserName {
            get {
                return ResourceManager.GetString("Outlook_TxtBx_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input#cred_userid_inputtext.
        /// </summary>
        internal static string Outlook_TxtBx_UserName_Css {
            get {
                return ResourceManager.GetString("Outlook_TxtBx_UserName_Css", resourceCulture);
            }
        }
    }
}
