//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDE.UITest.PageObjects {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SamplesPageCtrls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SamplesPageCtrls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDE.UITest.PageObjects.SamplesPageCtrls", typeof(SamplesPageCtrls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dpCollectionDate.
        /// </summary>
        internal static string DatePicker {
            get {
                return ResourceManager.GetString("DatePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgGeneralCommentEmpty.
        /// </summary>
        internal static string GeneralComment_Empty {
            get {
                return ResourceManager.GetString("GeneralComment_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgGeneralCommentFull.
        /// </summary>
        internal static string GeneralComment_Full {
            get {
                return ResourceManager.GetString("GeneralComment_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtGeneralCommentText.
        /// </summary>
        internal static string GeneralComment_Text {
            get {
                return ResourceManager.GetString("GeneralComment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblPECommentText.
        /// </summary>
        internal static string SampleParameterComment_Text {
            get {
                return ResourceManager.GetString("SampleParameterComment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _lblPELeftLimitValues.
        /// </summary>
        internal static string SampleParameterLeftLimit {
            get {
                return ResourceManager.GetString("SampleParameterLeftLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblPEUnitOfMeasure.
        /// </summary>
        internal static string SampleParameterMeasureUnit {
            get {
                return ResourceManager.GetString("SampleParameterMeasureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblPEDisplayName.
        /// </summary>
        internal static string SampleParameterName {
            get {
                return ResourceManager.GetString("SampleParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtPEReadingValue.
        /// </summary>
        internal static string SampleParameterReading {
            get {
                return ResourceManager.GetString("SampleParameterReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgPECommentEmpty.
        /// </summary>
        internal static string SampleParameterReadingComments_Empty {
            get {
                return ResourceManager.GetString("SampleParameterReadingComments_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgPECommentFull.
        /// </summary>
        internal static string SampleParameterReadingComments_Full {
            get {
                return ResourceManager.GetString("SampleParameterReadingComments_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _lblPERightLimitValues.
        /// </summary>
        internal static string SampleParameterRightLimit {
            get {
                return ResourceManager.GetString("SampleParameterRightLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgSLDownArrowMinus.
        /// </summary>
        internal static string SamplePoint_DownArrowMinus {
            get {
                return ResourceManager.GetString("SamplePoint_DownArrowMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgSLDownArrowPlus.
        /// </summary>
        internal static string SamplePoint_DownArrowPlus {
            get {
                return ResourceManager.GetString("SamplePoint_DownArrowPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgSLCommentEmpty.
        /// </summary>
        internal static string SamplePointComment_Empty {
            get {
                return ResourceManager.GetString("SamplePointComment_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgSLCommentFull.
        /// </summary>
        internal static string SamplePointComment_Full {
            get {
                return ResourceManager.GetString("SamplePointComment_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtSLGeneralComment.
        /// </summary>
        internal static string SamplePointComment_Text {
            get {
                return ResourceManager.GetString("SamplePointComment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblSLSampleLocationName.
        /// </summary>
        internal static string SamplePointName {
            get {
                return ResourceManager.GetString("SamplePointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgSamples.
        /// </summary>
        internal static string SamplesLable {
            get {
                return ResourceManager.GetString("SamplesLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgBack.
        /// </summary>
        internal static string SamplesLeftArrow {
            get {
                return ResourceManager.GetString("SamplesLeftArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgSave.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tpCollectionTime.
        /// </summary>
        internal static string TimePicker {
            get {
                return ResourceManager.GetString("TimePicker", resourceCulture);
            }
        }
    }
}
